### ISSUE TITLE
ERROR! 'check_mode' is not a valid attribute for a Task

### ISSUE THREAD

**Issue by icepaule** [gdamjan/ansible-uwsgi#10]
Hello gdamjan,

I'm having issues with your code and hoping you could help me out in getting it running...

ERROR! 'check_mode' is not a valid attribute for a Task

**The error appears to have been in '/opt/irma/ansible/roles/gdamjan.uwsgi/tasks/main.yml**': line 6, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:
**- name: Checking for uwsgi version**
  ^ here
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

I already had a look at your source file, but could not see any strange things. - Although I'm not a coder at all.  :-)

Thanks a lot for your help.

Marcus

**Comment by gdamjan** [comment]
what version of ansible do you have?

**Comment by icepaule** [comment]
Hi,
from _ansible --version_:
ansible 2.0.0.2
  config file = /opt/irma/ansible/ansible.cfg
  configured module search path = ./ansible_plugins/modules

Cheers and thx for your help.

Marcus

**Comment by gdamjan** [comment]
I can't see any problems with the tasks, maybe try a newer ansible? latest is 2.4.2

**Comment by icepaule** [comment]
looks like:
pip install -I ansible==2.0.2
did the job. The very latest ansible gave another error, but 2.0.2 worked.

Thanks a lot
Marcus
